### ISSUE TITLE
Cloned project, tried to run for the first time, got an error.....

### ISSUE THREAD

**Issue by lhoff** [oozcitak/canphotoblog#22]
node run.js

module.js:340
    throw err;
          ^
Error: Cannot find module './lib/app.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\Users\User001\test-pb-project\canphotoblog\run.js:1:73)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
PS C:\Users\User001\test-pb-project\canphotoblog>

**Comment by oozcitak** [comment]
Did you make the project?

```
cd canphotoblog
make
```
